---
title: "NPS_building_USGWD_wells_within_park"
author: "AAF"
date: "2026-04-01"
output: html_document
---

```{r}
# 1. Load Libraries
library(tidyverse)
library(sf)
library(mapview)

```

```{r}
# Pull in your custom functions
source("setup.R")
```

```{r}
# 1. Set Target Park
park <- "EVER"

# Get park boundary
pb <- getParkBoundary(park)

# 2. Create buffered AOI
aoi <- pb %>% 
  st_buffer(10000) 

# 3. Get Buildings
bldg_all <- getBuildings(park_boundary = pb) 

# # 4. Get State Boundary
# st <- tigris::states() %>% 
#   dplyr::filter(STUSPS %in% pb$STATE)

```


# ==========================================
# 5. DYNAMIC WELL FETCHING
# ==========================================

```{r}

state_name_fixed <- gsub(" ", "_", st$NAME)
well_file_path <- paste0("data/Water_Supply_Systems/USGWD-Tabular/USGWD_", state_name_fixed, ".csv")

# Load and crop the wells to the 10km BUFFER
aoi_wells <- read_csv(well_file_path, show_col_types = FALSE) %>%
  filter(!is.na(Longitude) & !is.na(Latitude)) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4269) %>%
  st_filter(aoi %>% st_transform(4269))

```

# ==========================================
# 6. NEW: WELLS STRICTLY INSIDE THE PARK
# ==========================================

```{r}


# Take the buffer wells and cookie-cutter them again using just 'pb'
park_wells_strict <- aoi_wells %>% 
  st_filter(pb %>% st_transform(4269))

```


# ==========================================
# 7. MAP EVERYTHING
# ==========================================

```{r}

mapview(aoi, layer.name = "10km Buffer (AOI)", col.regions = "yellow", alpha.regions = 0.3) +
  mapview(pb, layer.name = "Park Boundary", col.regions = "seagreen") +
  mapview(bldg_all %>% st_centroid(), layer.name = "Buildings", col.regions = "tomato") +
  mapview(aoi_wells, layer.name = "Wells in 10km Buffer", col.regions = "grey", cex = 3) +
  mapview(park_wells_strict, layer.name = "Wells INSIDE Park", col.regions = "blue", cex = 4)

```



